######################## default configuration ####################
# baseURL = "http://pur-freistadt.at/"
baseURL = "http://127.0.0.1/"
title = "PUR Freistadt"
theme = "bigspring-light"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

